# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171104_2311'),
        ('api', '0007_contact_img'),
    ]

    operations = [
    ]
